
import { TbBrandCSharp } from "react-icons/tb";
import { IconType } from "react-icons"
import {
  FaHtml5,
  FaCss3Alt,
  FaJsSquare,
  FaJava,
  FaPython,
  FaPhp,
  FaRust,
  FaSwift,
  FaFileCode,
  FaFileAlt,
} from "react-icons/fa";
import {
  SiC,
  SiCplusplus,
  SiGo,
  SiKotlin,
  SiRuby,
  SiPerl,
  SiLua,
  SiR,
  SiTypescript,
  SiGraphql,
} from "react-icons/si";

export type LanguageInfoType = {
  name: string;
  icon: IconType
};

// These are the programming languages that are common and are supported by Monaco code editor

export const codeLanguageInfo: { [key: string]: LanguageInfoType } = {
  bat: { name: "Batch", icon: FaFileCode },
  c: { name: "C", icon: SiC },
  cpp: { name: "C++", icon: SiCplusplus },
  csharp: { name: "C#", icon: TbBrandCSharp },
  css: { name: "CSS", icon: FaCss3Alt },
  dockerfile: { name: "Dockerfile", icon: FaFileCode },
  fsharp: { name: "F#", icon: FaFileCode },
  go: { name: "Go", icon: SiGo },
  graphql: { name: "GraphQL", icon: SiGraphql },
  handlebars: { name: "Handlebars", icon: FaFileCode },
  html: { name: "HTML", icon: FaHtml5 },
  ini: { name: "INI", icon: FaFileCode },
  java: { name: "Java", icon: FaJava },
  javascript: { name: "JavaScript", icon: FaJsSquare },
  json: { name: "JSON", icon: FaFileCode },
  kotlin: { name: "Kotlin", icon: SiKotlin },
  less: { name: "Less", icon: FaFileCode },
  lua: { name: "Lua", icon: SiLua },
  markdown: { name: "Markdown", icon: FaFileCode },
  objectivec: { name: "Objective-C", icon: FaFileCode },
  pascal: { name: "Pascal", icon: FaFileCode },
  perl: { name: "Perl", icon: SiPerl },
  php: { name: "PHP", icon: FaPhp },
  plaintext: { name: "Plain Text", icon: FaFileCode },
  powershell: { name: "PowerShell", icon: FaFileCode },
  python: { name: "Python", icon: FaPython },
  r: { name: "R", icon: SiR },
  razor: { name: "Razor", icon: FaFileCode },
  ruby: { name: "Ruby", icon: SiRuby },
  rust: { name: "Rust", icon: FaRust },
  scss: { name: "SCSS", icon: FaFileCode },
  shell: { name: "Shell Script", icon: FaFileCode },
  sql: { name: "SQL", icon: FaFileCode },
  swift: { name: "Swift", icon: FaSwift },
  typescript: { name: "TypeScript", icon: SiTypescript },
  vb: { name: "Visual Basic", icon: FaFileCode },
  xml: { name: "XML", icon: FaFileCode },
  yaml: { name: "YAML", icon: FaFileCode },
  txt: { name: "Text File", icon: FaFileAlt },
};

export const languageToExtension: Record<string, string> = {
  bat: "bat",
  c: "c",
  cpp: "cpp",
  csharp: "cs",
  css: "css",
  dockerfile: "dockerfile",
  fsharp: "fs",
  go: "go",
  graphql: "graphql",
  handlebars: "hbs",
  html: "html",
  ini: "ini",
  java: "java",
  javascript: "js",
  json: "json",
  kotlin: "kt",
  less: "less",
  lua: "lua",
  markdown: "md",
  objectivec: "m",
  pascal: "pas",
  perl: "pl",
  php: "php",
  plaintext: "txt",
  powershell: "ps1",
  python: "py",
  r: "r",
  razor: "cshtml",
  ruby: "rb",
  rust: "rs",
  scss: "scss",
  shell: "sh",
  sql: "sql",
  swift: "swift",
  typescript: "ts",
  vb: "vb",
  xml: "xml",
  yaml: "yml",
  txt: "txt",
}


export const extensionToLanguage: Record<string, string> = {
  bat: "bat",
  c: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  h: "cpp",
  hpp: "cpp",
  cs: "csharp",
  css: "css",
  dockerfile: "dockerfile",
  fs: "fsharp",
  go: "go",
  graphql: "graphql",
  gql: "graphql",
  hbs: "handlebars",
  html: "html",
  htm: "html",
  ini: "ini",
  java: "java",
  js: "javascript",
  jsx: "javascript",
  json: "json",
  kt: "kotlin",
  kts: "kotlin",
  less: "less",
  lua: "lua",
  md: "markdown",
  markdown: "markdown",
  m: "objectivec",
  mm: "objectivec",
  pas: "pascal",
  p: "pascal",
  pl: "perl",
  pm: "perl",
  php: "php",
  txt: "plaintext",
  text: "plaintext",
  ps1: "powershell",
  psm1: "powershell",
  py: "python",
  r: "r",
  cshtml: "razor",
  rb: "ruby",
  rs: "rust",
  scss: "scss",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  sql: "sql",
  swift: "swift",
  ts: "typescript",
  tsx: "typescript",
  vb: "vb",
  xml: "xml",
  xsd: "xml",
  svg: "xml",
  yml: "yaml",
  yaml: "yaml",
}
